[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = { version = "1.33.0", features = ["full"] }
reqwest = { version = "0.11" }
tokio-tungstenite = { version="0.20", features = ["native-tls"]}
serde_json = "1.0"